from sqlite3 import connect, IntegrityError
